# Homework 4

**ÖNEMLİ:** Beyler aşağıda her bölümde yapılması gereken seyleri belirttim. Herkes tamamladığı kısımların üstünü çift tilda (\~~) ile çizerse geriye ne kalmış anlayabiliriz. Ayrıca **OutputTable** adında bir class olusturdum, output table olusturmak icin uzun uzun yazmanıza gerek yok kullanımına BFGS kodundan bakabilirsiniz.

Yazıyı okuyanlar isminin üstünü cizebilirse herkes okuyunca bu yazıyı silebiliriz.:
*   Sefa
*   Yunus
*   Harun
*   ~~Akın~~

### TODOs

Steepest Descent:
*   Algorithm code
*   Function 1 - Solution set 1
*   Function 1 - Solution set 2
*   Function 2 - Solution set 1
*   Function 2 - Solution set 2

Newton's Method:
*   Algorithm code
*   Function 1 - Solution set 1
*   Function 1 - Solution set 2
*   Function 2 - Solution set 1
*   Function 2 - Solution set 2

DFP:
*   Algorithm code
*   Function 1 - Solution set 1
*   Function 1 - Solution set 2
*   Function 2 - Solution set 1
*   Function 2 - Solution set 2  

BFGS:
*   ~~Algorithm code~~
*   Function 1 - Solution set 1
*   Function 1 - Solution set 2
*   Function 2 - Solution set 1
*   Function 2 - Solution set 2

In [14]:
import pandas as pd
import numpy as np
from sympy import Symbol, lambdify

In [15]:
x1 = Symbol("x1")
x2 = Symbol("x2")

func1 = (5*x1 - x2)**4 + (x1 - 2)**2 + x1 - 2*x2 + 12
func2 = 100*(x2 - x1**2)**2 + (1 - x1)**2 


f1 = lambdify([[x1,x2]], func1, "numpy")
f2 = lambdify([[x1,x2]], func2, "numpy")

grad_f1 = lambdify([[x1,x2]], func1.diff([[x1, x2]]), "numpy")
grad_f2 = lambdify([[x1,x2]], func2.diff([[x1, x2]]), "numpy")

### Useful Functions

In [55]:
def np_str(x_k):
    '''
    Used to convert numpy array to string with determined format
    '''
    return np.array2string(x_k, precision=3, separator=',')

In [17]:
class OutputTable:
    def __init__(self):
        self.table = pd.DataFrame([],columns=['k', 'x^k', 'f(x^k)', 'd^k', 'a^k', 'x^k+1'])
    def add_row(self, k, xk, fxk, dk, ak, xkp):
        self.table.loc[len(self.table)] = [k, np_str(xk), fxk, np_str(dk), ak, np_str(xkp)]
    def print_latex(self):
        print(self.table.to_latex(index=True,float_format='%.3f'))

### Exact Line Search

In [18]:
def BisectionMethod(f, a=-100,b=100,epsilon=0.005) :
    iteration=0
    while (b - a) >= epsilon:
        x_1 = (a + b) / 2
        fx_1 = f(x_1)
        if f(x_1 + epsilon) <= fx_1:
            a = x_1
        else:
            b = x_1
        iteration+=1
    x_star = (a+b)/2
    return x_star

def ExactLineSearch(f, x0, d):
    alpha = Symbol('alpha')
    function_alpha = f(np.array(x0)+alpha*np.array(d))
    f_alp = lambdify(alpha, function_alpha, 'numpy')
    alp_star = BisectionMethod(f_alp)
    return alp_star

## Steepest Descent Method

## Newton's Method

## DFP

In [8]:
def DFP(f, grad_f, x_0, epsilon):
    k = 0
    H = np.identity(len(x_0))
    print(H)

In [10]:
DFP(f1, f1, [0,2,2], 0.02)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
Akin kardesime selam olsun. 4. Katta bulusmak uzere...
                                Sevgiler
                                 Harun

## BFGS

In [56]:
def BFGS(f, grad_f, x_0, epsilon):
    xk = np.array(x_0)
    k = 0
    H = np.identity(len(x_0))
    stop = False
    output = OutputTable()
    while(stop == False):
        d = -H @ np.transpose(grad_f(xk))
        if(np.linalg.norm(d) < epsilon):
            stop = True
            output.add_row(k,xk,f(xk),d,None,np.array([]))
        else:
            a = ExactLineSearch(f,xk,d)
            xkp = xk + a*d
            p = xkp - xk
            q = np.transpose(grad_f(xkp)) - np.transpose(grad_f(xk))
            A = (1+ np.transpose(q) @ H @ q) / (np.transpose(q) @ p) * (p @ np.transpose(p)) / (np.transpose(p) @ q)
            B = - (p @ np.transpose(q) * H + H @ q @ np.transpose(p)) * (1 / (np.transpose(q) @ p))
            Hkp = H + A + B
            output.add_row(k, xk, f(xk), d, a, xkp)
            k += 1
            xk = xkp
            H = Hkp
    return xk, f(xk), output


In [60]:
xs1, fs1, output1 = BFGS(f1, grad_f1, [0,0], 0.005)

In [63]:
xs1, fs1

(array([0.1549415 , 0.11069101]), 15.532208936619384)

In [62]:
output1.table

k              x^k   f(x^k)                    d^k         a^k  \
0    0            [0,0]       16                [3.,2.]   0.0442505   
1    1    [0.133,0.089]  15.5519          [1.798,1.798]   0.0106812   
2    2    [0.152,0.108]  15.5326          [0.255,0.255]   0.0106812   
3    3    [0.155,0.11 ]  15.5322          [1.071,1.071] -0.00152588   
4    4    [0.153,0.109]  15.5324        [17.239,17.239] -0.00152588   
5    5    [0.127,0.082]  15.5632          [1.147,1.147]   0.0228882   
6    6    [0.153,0.109]  15.5324          [0.096,0.096]   0.0198364   
7    7    [0.155,0.111]  15.5322          [0.681,0.681] -0.00152588   
8    8    [0.154,0.11 ]  15.5323        [24.631,24.631] -0.00152588   
9    9    [0.116,0.072]  15.5879          [0.813,0.813]   0.0442505   
10  10    [0.152,0.108]  15.5325            [0.08,0.08]   0.0320435   
11  11    [0.155,0.111]  15.5322          [0.649,0.649] -0.00152588   
12  12    [0.154,0.11 ]  15.5323        [27.734,27.734] -0.00152588   
13  13    [0.112,0.067]  15.6011          [0.743,0.743]   0.0564575   
14  14    [0.153,0.109]  15.5323          [0.035,0.035]   0.0411987   
15  15    [0.155,0.111]  15.5322          [1.191,1.191] -0.00152588   
16  16    [0.153,0.109]  15.5324        [13.609,13.609] -0.00152588   
17  17    [0.132,0.088]  15.5526          [1.426,1.426]   0.0137329   
18  18    [0.152,0.108]  15.5326          [0.251,0.251]   0.0106812   
19  19    [0.155,0.11 ]  15.5322          [1.422,1.422] -0.00152588   
20  20    [0.152,0.108]  15.5325        [12.982,12.982] -0.00152588   
21  21    [0.133,0.088]  15.5521          [1.558,1.558]   0.0106812   
22  22    [0.149,0.105]  15.5336          [0.655,0.655]  0.00762939   
23  23    [0.154,0.11 ]  15.5322          [0.768,0.768] -0.00152588   
24  24    [0.153,0.109]  15.5324        [33.317,33.317] -0.00152588   
25  25    [0.102,0.058]    15.63          [0.671,0.671]   0.0747681   
26  26    [0.152,0.108]  15.5325          [0.047,0.047]   0.0534058   
27  27    [0.155,0.111]  15.5322          [0.391,0.391] -0.00152588   
28  28    [0.154,0.11 ]  15.5322        [45.715,45.715] -0.00152588   
29  29    [0.085,0.04 ]  15.6943          [0.524,0.524]    0.132751   
30  30    [0.154,0.11 ]  15.5322            [0.01,0.01]   0.0839233   
31  31    [0.155,0.111]  15.5322          [0.797,0.797] -0.00152588   
32  32    [0.154,0.11 ]  15.5323        [19.488,19.488] -0.00152588   
33  33    [0.124,0.08 ]   15.569          [0.991,0.991]   0.0289917   
34  34    [0.153,0.109]  15.5324          [0.093,0.093]   0.0228882   
35  35    [0.155,0.111]  15.5322          [0.627,0.627] -0.00152588   
36  36    [0.154,0.11 ]  15.5323        [27.368,27.368] -0.00152588   
37  37    [0.112,0.068]  15.5993          [0.747,0.747]   0.0534058   
38  38    [0.152,0.108]  15.5326          [0.073,0.073]    0.038147   
39  39    [0.155,0.111]  15.5322          [0.401,0.401] -0.00152588   
40  40    [0.154,0.11 ]  15.5322        [46.123,46.123] -0.00152588   
41  41    [0.084,0.04 ]  15.6969          [0.522,0.522]    0.132751   
42  42    [0.153,0.109]  15.5323          [0.021,0.021]   0.0808716   
43  43    [0.155,0.111]  15.5322          [0.587,0.587] -0.00152588   
44  44    [0.154,0.11 ]  15.5322        [28.008,28.008] -0.00152588   
45  45    [0.111,0.067]  15.6018          [0.731,0.731]   0.0564575   
46  46    [0.153,0.108]  15.5325          [0.058,0.058]   0.0411987   
47  47    [0.155,0.111]  15.5322            [0.29,0.29] -0.00152588   
48  48    [0.154,0.11 ]  15.5322        [60.492,60.492] -0.00457764   
49  49  [-0.122,-0.167]  16.7549          [0.304,0.304]    0.907898   
50  50    [0.154,0.11 ]  15.5323          [0.004,0.004]    0.248718   
51  51    [0.155,0.111]  15.5322            [0.13,0.13] -0.00152588   
52  52    [0.155,0.111]  15.5322      [119.817,119.817] -0.00457764   
53  53  [-0.394,-0.438]  23.6982          [0.032,0.032]     17.3111   
54  54    [0.155,0.111]  15.5322  [2.854e-06,2.854e-06]        None   

              x^k+1  
0     