In [1]:
import pandas as pd
import numpy as np
from sympy import Symbol, lambdify

In [7]:
x1 = Symbol("x1")
x2 = Symbol("x2")

func1 = (5*x1 - x2)**2 + (x1 - 2)**2 + x1 - 2*x2 + 12
func2 = 100*(x2 - x1**2) + (1 - x1**2) 


f1 = lambdify([[x1,x2]], func1, "numpy")
f2 = lambdify([[x1,x2]], func2, "numpy")

grad_f1 = lambdify([[x1,x2]], func1.diff([x1, x2]), "numpy")
grad_f2 = lambdify([[x1,x2]], func2.diff([x1, x2]), "numpy")

### Exact Line Search

In [3]:
def BisectionMethod(f, a=-100,b=100,epsilon=0.005) :
    iteration=0
    while (b - a) >= epsilon:
        x_1 = (a + b) / 2
        fx_1 = f(x_1)
        if f(x_1 + epsilon) <= fx_1:
            a = x_1
        else:
            b = x_1
        iteration+=1
    x_star = (a+b)/2
    return x_star

def ExactLineSearch(f, x0, d):
    alpha = Symbol('alpha')
    function_alpha = f(np.array(x0)+alpha*np.array(d))
    f_alp = lambdify(alpha, function_alpha, 'numpy')
    alp_star = BisectionMethod(f_alp)
    return alp_star

### DFP

In [8]:
def DFP(f, grad_f, x_0, epsilon):
    k = 0
    H = np.identity(len(x_0))
    print(H)

In [10]:
DFP(f1, f1, [0,2,2], 0.02)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
Akin kardesime selam olsun. 4. Katta bulusmak uzere...
                                Sevgiler
                                 Harun